### ISSUE TITLE
Group rectangles

### ISSUE THREAD

**Issue by antofa** [4rtzel/poe-archnemesis-scanner#10]
![изображение](https://user-images.githubusercontent.com/890217/153574690-5425bd68-79fb-4cc8-a0ea-81f373231116.png)

16 berserkers found, but actually 7 is in inventory

Seems you don't group rectangles with cv2, do you?

For example:
```
def get_rectangles(image, template, THRESHOLD = 0.8):
    result = cv2.matchTemplate(image, template, cv2.TM_CCOEFF_NORMED)
    yloc, xloc = np.where(result >= THRESHOLD)

    rectangles = []

    [ht, wt] = template.shape
    for (x, y) in zip(xloc, yloc):
        rectangles.append([int(x), int(y), int(wt), int(ht)])
        rectangles.append([int(x), int(y), int(wt), int(ht)])

    rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.1)

    return rectangles
```

**Comment by 4rtzel** [comment]
Could you explain what does it do exactly?

As far as I understand, it should eliminate possible overlapping rectangles?

It's also interesting that it's first time I'm seeing the algorithm detects the same inventory item as multiple matches. Could you provide a little bit more info about your setup?

**Comment by antofa** [comment]
![изображение](https://user-images.githubusercontent.com/890217/153625347-05951450-9954-47d2-95c8-3e1c41a95fcf.png)

yes, it is for groupping close rectangles

windows 10, i dont know what is correct scale rate for my window (1920x1040 paint says)

**Comment by 4rtzel** [comment]
The support for the windowed version should arrive soon. Hope it will help it your case.

**Comment by 4rtzel** [comment]
@antofa, I've added the implementation for rectangle grouping in 65bb088. Could you please take a look and validate that the code is correct? After that, I'll close this issue.
