### ISSUE TITLE
Entangler not detected

### ISSUE THREAD

**Issue by vaelrock** [4rtzel/poe-archnemesis-scanner#15]
Thank you again for this league-changing tool. Version 0.0.3 has everything needed to be optimal and not lose time in maps.
The new recipe tree idea is brilliant.
Everything's perfect for me except for Entangler not being detected correctly, even when changing the threshold or image scale.

**Comment by 4rtzel** [comment]
Could you look at the console output to see the 'Best match' for Entangler modifier? It may be a problem with confidence threshold being to high for your setup. You could try lowering in by 0.01 until it works.

**Comment by 4rtzel** [comment]
Yeah, I just realized that a minute ago. Trying to validate all other pictures. It's hard to find good source images online unfortunately.

**Comment by 4rtzel** [comment]
Updated the picture in the repository: https://github.com/4rtzel/poe-archnemesis-scanner/blob/master/pictures/Entangler.png

You can download in manually and replace the one in your `pictures` folder while I'm preparing the next update (d9e93fe)

**Comment by rulerhao** [comment]
Awesome!

**Comment by 4rtzel** [comment]
New release is out: https://github.com/4rtzel/poe-archnemesis-scanner/releases/tag/v0.1.0. Closing this issue.
