### ISSUE TITLE
[GitHub] Improvement to GitHub usage.

### ISSUE THREAD

**Issue by andr9528** [4rtzel/poe-archnemesis-scanner#19]
It would appear that your experience using GitHub is low, from how few repositories you have . As such i have a few suggestion, to improve readability for you and others visiting the GitHub. You already got the hang of Markdown it would seems from the Readme on the frontpage. Markdown can be used anywhere on GitHub, afaik.

At the moment you are adding things like "Bug" and "Feature Request" in the titel. 
This can be easiliy done by adding Labels to an Issues. By default, afaik, there exists 9 different Labels, but you can freely create more as needed. Among the default ones exists "Bug", for Bugs, and "Enhancement" for Feature Requests. As the owner of this GitHub repository, you can add Labels while creating an issues, and on existing issues.
Labels can also be sorted by, so you can easier find all the ones labeled bugs or anything else.
![Skærmbillede 2022-02-12 105459](https://user-images.githubusercontent.com/21788044/153706711-dfa6ff6a-6b92-408f-8287-bc7d8725133c.png)

I'd also suggest enabling "Discussions" in the settings. This adds another tap, just like Issues, where users can discuss anything. This would be an ideal area get feedback from user through, or discuss any changes you might be working on with users.
![Skærmbillede 2022-02-12 104344](https://user-images.githubusercontent.com/21788044/153706794-ab7ba1bc-4bc1-46de-98d4-3ec31fd812cf.png)

Hope you like my suggestions.

**Comment by 4rtzel** [comment]
Yes, you are right. I'm not that well acquainted with github workflow. Thank you for taking your time writing this, I'll apply your suggestions.
