### ISSUE TITLE
[Bug] Able to open multiple Settings

### ISSUE THREAD

**Issue by andr9528** [4rtzel/poe-archnemesis-scanner#20]
Settings can be clicked multiple times to open Settings multiple times.
Only the most recent settings can be closed. Has to exit Tool to close others.

Using Windows 11, with following display settings.
![image](https://user-images.githubusercontent.com/21788044/153707331-dbb28e96-cde3-473d-ab13-954285fc1f30.png)

**Comment by 4rtzel** [comment]
Fixed in 0efa155 and included in the new release: https://github.com/4rtzel/poe-archnemesis-scanner/releases/tag/v0.1.0. Closing this issue.
