### ISSUE TITLE
Trigger scan on keybind with delay.

### ISSUE THREAD

**Issue by Davst** [4rtzel/poe-archnemesis-scanner#23]
If we could trigger a scan on a keybind, with a delay you could keybind the to the archnemesis inventory key and auto scan when you opened it.

**Comment by 4rtzel** [comment]
Please use this issue to discuss key binding feature: https://github.com/4rtzel/poe-archnemesis-scanner/issues/14. Would like to pile up all the suggestion in one place before starting working on it.
