### ISSUE TITLE
Green markers block clicks

### ISSUE THREAD

**Issue by Davst** [4rtzel/poe-archnemesis-scanner#24]
The green markers that also seem to have no way to get rid of block interactions.

So once you've clicked a recipie, you are blocked from interacting with the items you want.

Also recipie trees seem to not be closable.. I can't get rid of green markers or some trees with any interaction but closing the app.

**Comment by 4rtzel** [comment]
By the green marks you mean the highlights on top of the inventory window? Is so, they should be destroyed automatically when you move the cursor from the recipe.

**Comment by 4rtzel** [comment]
I think I was able to reproduce the issue. If you click on the "green" item in the tree, than the green highlight won't go away. Should be able to fix that quite easily.

**Comment by Davst** [comment]
Yeah that sounds like the Interaction i was exploring

**Comment by 4rtzel** [comment]
Fixed in c3c4f30 and included in the new release: https://github.com/4rtzel/poe-archnemesis-scanner/releases/tag/v0.1.0. Closing this issue.
