### ISSUE TITLE
[Enhancement] Ingredient used in

### ISSUE THREAD

**Issue by andr9528** [4rtzel/poe-archnemesis-scanner#25]
At the moment when you left click an recipe or ingredient, when displaying inventory items, it shows how to make what was clicked.

It would be cool with the ability to show what something that was clicked is used for. 
This could be done on click with mouse button three or maybe left click while holding shift or something similar.

i.e clicking a "Toxic", would show two combination, one to make "Entangler" and one for "Treant Horde".

**Comment by 4rtzel** [comment]
Yeah, I thought about that. My idea was to display the "parent" ingredient on the right or the top of the tree. Something like that:

![example](https://i.imgur.com/YPGOdyG.png)

**Comment by 4rtzel** [comment]
Implemented in 777fcbc and included in the new release: https://github.com/4rtzel/poe-archnemesis-scanner/releases/tag/v0.1.0. Closing this issue.
