### ISSUE TITLE
Solaris-touched can't be recognized

### ISSUE THREAD

**Issue by Shiningingy** [4rtzel/poe-archnemesis-scanner#26]
Reason: the picture in the doc file is incompatible with the actual picture in-game.
Fix: Replace with the one download from poedb

**Comment by Shiningingy** [comment]
I found a possible solution to the recognized problem since the item level block part of the icon, which is setting a lower confidence threshold for those confusing icons.
CONFUSED_ITEMS = ['Kitava-Touched','Innocence-Touched','Shakari-Touched','Abberath-Touched','Tukohama-Touched','Brine King-Touched','Solaris-Touched','Lunaris-Touched','Storm Strider','Assassin']
I'm using a 0.04 lower standard for those items while the threshold for other icons remains at 0.94.
Also, there exist some(about 2~3) 48*48 images in the picture folder, those items are hard to be scanned out.
I'm using all 48*48 icons and changing the scale multiplier to 1.65 which result in 1.1090625 scale multiplier for 1080p
Under those settings the scanner working perfectly, I'm still testing outliers. :3

**Comment by 4rtzel** [comment]
Please refer to this comment: https://github.com/4rtzel/poe-archnemesis-scanner/issues/22#issuecomment-1037478826

You could download the new images manually and put them in `pictures` directory while waiting for the new update.

I'll keep this issue open until the new release.

**Comment by kevindevm** [comment]
> 'm using all 48x48 icons
can you shared them? or point me where i can find them

**Comment by kevindevm** [comment]
so this is a buff tried those and still missing some and bloodletter taking as bloodletter and frenzied

@4rtzel can you add a way that if u match the slot as "frenzied" or any save that confidence and if that slot got again math as anything else take the highest confidence in to that slot
that maybe will fix the same item counting for two or more

**Comment by 4rtzel** [comment]
Fixed Solaris-Touched image in 0a1960b and included in the new release: https://github.com/4rtzel/poe-archnemesis-scanner/releases/tag/v0.1.0. Closing this issue.

@kevindevm, please try a new version and if you still encounter the problem, feel free to open a new issue.
