### ISSUE TITLE
little help try different combination no work correctly for me 

### ISSUE THREAD

**Issue by hiro01dzdvb** [4rtzel/poe-archnemesis-scanner#30]
HELLO i try different combination nothing help to fixe it little help pls 

![image](https://user-images.githubusercontent.com/49050168/153728519-962490ec-f9e1-4f57-9b83-ae4f6ed16c71.png)
![image](https://user-images.githubusercontent.com/49050168/153728529-53bdab3b-2753-463b-b827-a97044f93cb0.png)
![image](https://user-images.githubusercontent.com/49050168/153728531-9266a90b-e0f1-47a8-bac1-b90355145368.png)

Thanks you

**Comment by 4rtzel** [comment]
The confidence threshold is way too low. Try setting it between 0.90 and 0.94 (the higher, the better).

**Comment by hiro01dzdvb** [comment]
start downgrading from 0.94 to 0.7 with 0.7 i got the the scan work without it not work 

![4](https://user-images.githubusercontent.com/49050168/153728901-579d5973-906f-46e4-8c60-7bbd564834d2.jpg)
![5](https://user-images.githubusercontent.com/49050168/153728903-8f53685e-bf4d-43a1-8d78-8731d47aa3a4.jpg)

thanks

**Comment by 4rtzel** [comment]
0.7 is way too low. It will think that anything is a match (which you can see happened in your case with x24 Berserker detected). I'd say the value should never be lower than 0.88. Another question: what is your image scale parameter?

**Comment by 4rtzel** [comment]
The scale parameter seems fine for your resolution. Could you try running the game in windowed fullscreen mode? The tool should support windowed mode just fine but it never hurts to try.

I can only suspect that something is wrong with image grab function because confidence values are way too low for your parameters.

**Comment by hiro01dzdvb** [comment]
i make some adjustement on it 
95, 310, 460, 450
0.6825
0.9

work perfectly thanks alot for your time and work

**Comment by 4rtzel** [comment]
Glad you make it work! Some recipes may be missing because of the wrong images in the `pictures` folder. You may want to take a look at this comment: https://github.com/4rtzel/poe-archnemesis-scanner/issues/22#issuecomment-1037478826

**Comment by hiro01dzdvb** [comment]
well thats work realy apreciate the help and the work :) awesome

**Comment by 4rtzel** [comment]
You're welcome! I'll close this issue then. Feel free to open another one if you encounter other problems.
