### ISSUE TITLE
Don't work properly in QHD resolution

### ISSUE THREAD

**Issue by forcer99** [4rtzel/poe-archnemesis-scanner#34]
Hi.
I can't run this scanner properly. Squares are not fit the emblems, I suppose due to QHD resolution.
Can you please advise how to deal this
![Безымянный](https://user-images.githubusercontent.com/99589803/153770740-5ad0998e-da22-434f-ae26-b3375affb7b8.png)
?

**Comment by 4rtzel** [comment]
Are you using window ui scale feature? If so, check this comment: https://github.com/4rtzel/poe-archnemesis-scanner/issues/3#issuecomment-1035917756

**Comment by meepen** [comment]
can you test it with the changes I made here? #35

**Comment by forcer99** [comment]
> Are you using window ui scale feature? If so, check this comment: [#3 (comment)](https://github.com/4rtzel/poe-archnemesis-scanner/issues/3#issuecomment-1035917756)

Thanks alot! Scaling in exe file works well!
