### ISSUE TITLE
count max 1 per slot, show warning if there is no match for some? show total matchs

### ISSUE THREAD

**Issue by kevindevm** [4rtzel/poe-archnemesis-scanner#39]
*so first of all maybe you can add some that check if slot number x already got a match and a new match for same slot come take the best one and ignore the other one

*show the total count of match can help so ppl know that the scan is not 100% real

*maybe show "7x unnacounted" if 7 slot had not match

here you can check what i mean
![Sin título](https://user-images.githubusercontent.com/7692819/153972283-abc8ed11-d5bd-4470-b359-ab3d047935de.png)

**Comment by kevindevm** [comment]
also  you named empowered minions and is empowering minions 
and the copy to clipboard seems to fail if a space is copied like 
![image](https://user-images.githubusercontent.com/7692819/153987137-fb9e1205-3017-4a1a-b2a7-b547dcedab87.png)
replacing " " with "\s" fix this
![image](https://user-images.githubusercontent.com/7692819/153987159-5b58e9f4-7f4f-4fd5-acc6-fea7592582bf.png)

**Comment by 4rtzel** [comment]
One item per slot is something [meepen](https://github.com/meepen) been working on here https://github.com/4rtzel/poe-archnemesis-scanner/pull/35.
