### ISSUE TITLE
Error when scanning inventory

### ISSUE THREAD

**Issue by drac69** [4rtzel/poe-archnemesis-scanner#43]
Just downloaded the latest commit and getting this error message when I press "Scan"

[https://pastebin.com/cNkMA2NN](url)

Not sure which commit is the cause, but yesterday it was scanning properly

**Comment by 4rtzel** [comment]
I merged a big patch yesterday (https://github.com/4rtzel/poe-archnemesis-scanner/pull/37) but I thought the exact same error was fixed. I'll look into it.

**Comment by 4rtzel** [comment]
Fixed here: bf86d72.
