### ISSUE TITLE
Try to translate into simplified Chinese(zh-cn)

### ISSUE THREAD

**Issue by RoyXin** [4rtzel/poe-archnemesis-scanner#49]
Hello, I'm trying to translate this software into Chinese. Would you mind?
I posted it on website "17173", a Chinese forum website about Poe,
Of course, I will indicate the author and source.

this is the link:   http://bbs.17173.com/thread-11336859-1-1.html

(sry, my english is pretty poor).

**Comment by 4rtzel** [comment]
No, I don't mind at all. Glad other people would be able to use it as well.

You might be interested in checking out this project: https://github.com/njes9701/poe_arch_scanner_zh_tw. It's a little behind the master but still something that might be useful to you.

**Comment by RoyXin** [comment]
thx
