### ISSUE TITLE
Error with column 7 and 8

### ISSUE THREAD

**Issue by eric-engberg** [4rtzel/poe-archnemesis-scanner#56]
The tool currently thinks items that are in column 8 are in column 7 and all of column 8 reports as "empty"

Resolution is 1920x1080

**Comment by 4rtzel** [comment]
Could you provide a screenshot with the output from console?

**Comment by eric-engberg** [comment]
`row=1, column=1, item=Treant Horde, confidence=0.9403691291809082
row=1, column=2, item=Shakari-Touched, confidence=0.9385910630226135
row=1, column=3, item=Brine King-Touched, confidence=0.9453920722007751
row=1, column=4, item=Echoist, confidence=0.9647418856620789
row=1, column=5, item=Lunaris-Touched, confidence=0.959652304649353
row=1, column=6, item=Juggernaut, confidence=0.9553692936897278
row=1, column=7, item=Berserker, confidence=0.9680625796318054
row=1, column=8 is empty
row=2, column=1, item=Toxic, confidence=0.9654670357704163
row=2, column=2, item=Mana Siphoner, confidence=0.9525712132453918
row=2, column=3, item=Assassin, confidence=0.9353207349777222
row=2, column=4, item=Arakaali-Touched, confidence=0.9432196617126465
row=2, column=5, item=Invulnerable, confidence=0.9408747553825378
row=2, column=6, item=Flameweaver, confidence=0.9616667628288269
row=2, column=7, item=Ice Prison, confidence=0.9493449926376343
row=2, column=8 is empty
row=3, column=1, item=Flameweaver, confidence=0.9616597294807434
row=3, column=2, item=Gargantuan, confidence=0.9595344066619873
row=3, column=3, item=Deadeye, confidence=0.9633416533470154
row=3, column=4, item=Rejuvenating, confidence=0.9368175864219666
row=3, column=5, item=Stormweaver, confidence=0.9587519764900208
row=3, column=6, item=Juggernaut, confidence=0.9553526639938354
row=3, column=7, item=Consecrator, confidence=0.9594808220863342
row=3, column=8 is empty
row=4, column=1, item=Brine King-Touched, confidence=0.9453783631324768
row=4, column=2, item=Flame Strider, confidence=0.9557751417160034
row=4, column=3, item=Gargantuan, confidence=0.9595315456390381
row=4, column=4, item=Storm Strider, confidence=0.94167560338974
row=4, column=5, item=Entangler, confidence=0.9424537420272827
row=4, column=6, item=Shakari-Touched, confidence=0.9385915994644165
row=4, column=7, item=Deadeye, confidence=0.963359534740448
row=4, column=8 is empty
row=5, column=1, item=Malediction, confidence=0.9649650454521179
row=5, column=2, item=Overcharged, confidence=0.9559146761894226
row=5, column=3, item=Frostweaver, confidence=0.955915629863739
row=5, column=4, item=Berserker, confidence=0.9680627584457397
row=5, column=5, item=Drought Bringer, confidence=0.9359319806098938
row=5, column=6, item=Mirror Image, confidence=0.946557343006134
row=5, column=7, item=Incendiary, confidence=0.9625879526138306
row=5, column=8 is empty
row=6, column=1, item=Gargantuan, confidence=0.9595369696617126
row=6, column=2, item=Mana Siphoner, confidence=0.9525582790374756
row=6, column=3, item=Incendiary, confidence=0.9625759124755859
row=6, column=4, item=Incendiary, confidence=0.9625638723373413
row=6, column=5, item=Sentinel, confidence=0.9607686996459961
row=6, column=6, item=Gargantuan, confidence=0.9595344066619873
row=6, column=7, item=Malediction, confidence=0.96497642993927
row=6, column=8 is empty
row=7, column=1, item=Echoist, confidence=0.9647418856620789
row=7, column=2, item=Rejuvenating, confidence=0.9368439316749573
row=7, column=3, item=Hasted, confidence=0.9600146412849426
row=7, column=4, item=Heralding Minions, confidence=0.9476842880249023
row=7, column=5, item=Frostweaver, confidence=0.9559152722358704
row=7, column=6, item=Chaosweaver, confidence=0.9619263410568237
row=7, column=7, item=Arcane Buffer, confidence=0.9690552949905396
row=7, column=8 is empty
row=8, column=1, item=Echoist, confidence=0.9647416472434998
row=8, column=2, item=Overcharged, confidence=0.9559146761894226
row=8, column=3, item=Overcharged, confidence=0.9559146761894226
row=8, column=4, item=Rejuvenating, confidence=0.9368469715118408
row=8, column=5, item=Echoist, confidence=0.9647283554077148
row=8, column=6, item=Steel-Infused, confidence=0.9543660879135132
row=8, column=7, item=Deadeye, confidence=0.9633563756942749
row=8, column=8 is empty
Missing Items: []`

**Comment by eric-engberg** [comment]
row=1, column=1, item=Treant Horde, confidence=0.9403691291809082
row=1, column=2, item=Shakari-Touched, confidence=0.9385910630226135
row=1, column=3, item=Brine King-Touched, confidence=0.9453920722007751
row=1, column=4, item=Echoist, confidence=0.9647418856620789
row=1, column=5, item=Lunaris-Touched, confidence=0.959652304649353
row=1, column=6, item=Juggernaut, confidence=0.9553692936897278
row=1, column=7, item=Berserker, confidence=0.9680625796318054
row=1, column=8 is empty
row=2, column=1, item=Toxic, confidence=0.9654670357704163
row=2, column=2, item=Mana Siphoner, confidence=0.9525712132453918
row=2, column=3, item=Assassin, confidence=0.9353207349777222
row=2, column=4, item=Arakaali-Touched, confidence=0.9432196617126465
row=2, column=5, item=Invulnerable, confidence=0.9408747553825378
row=2, column=6, item=Flameweaver, confidence=0.9616667628288269
row=2, column=7, item=Ice Prison, confidence=0.9493449926376343
row=2, column=8 is empty
row=3, column=1, item=Flameweaver, confidence=0.9616597294807434
row=3, column=2, item=Gargantuan, confidence=0.9595344066619873
row=3, column=3, item=Deadeye, confidence=0.9633416533470154
row=3, column=4, item=Rejuvenating, confidence=0.9368175864219666
row=3, column=5, item=Stormweaver, confidence=0.9587519764900208
row=3, column=6, item=Juggernaut, confidence=0.9553526639938354
row=3, column=7, item=Consecrator, confidence=0.9594808220863342
row=3, column=8 is empty
row=4, column=1, item=Brine King-Touched, confidence=0.9453783631324768
row=4, column=2, item=Flame Strider, confidence=0.9557751417160034
row=4, column=3, item=Gargantuan, confidence=0.9595315456390381
row=4, column=4, item=Storm Strider, confidence=0.94167560338974
row=4, column=5, item=Entangler, confidence=0.9424537420272827
row=4, column=6, item=Shakari-Touched, confidence=0.9385915994644165
row=4, column=7, item=Deadeye, confidence=0.963359534740448
row=4, column=8 is empty
row=5, column=1, item=Malediction, confidence=0.9649650454521179
row=5, column=2, item=Overcharged, confidence=0.9559146761894226
row=5, column=3, item=Frostweaver, confidence=0.955915629863739
row=5, column=4, item=Berserker, confidence=0.9680627584457397
row=5, column=5, item=Drought Bringer, confidence=0.9359319806098938
row=5, column=6, item=Mirror Image, confidence=0.946557343006134
row=5, column=7, item=Incendiary, confidence=0.9625879526138306
row=5, column=8 is empty
row=6, column=1, item=Gargantuan, confidence=0.9595369696617126
row=6, column=2, item=Mana Siphoner, confidence=0.9525582790374756
row=6, column=3, item=Incendiary, confidence=0.9625759124755859
row=6, column=4, item=Incendiary, confidence=0.9625638723373413
row=6, column=5, item=Sentinel, confidence=0.9607686996459961
row=6, column=6, item=Gargantuan, confidence=0.9595344066619873
row=6, column=7, item=Malediction, confidence=0.96497642993927
row=6, column=8 is empty
row=7, column=1, item=Echoist, confidence=0.9647418856620789
row=7, column=2, item=Rejuvenating, confidence=0.9368439316749573
row=7, column=3, item=Hasted, confidence=0.9600146412849426
row=7, column=4, item=Heralding Minions, confidence=0.9476842880249023
row=7, column=5, item=Frostweaver, confidence=0.9559152722358704
row=7, column=6, item=Chaosweaver, confidence=0.9619263410568237
row=7, column=7, item=Arcane Buffer, confidence=0.9690552949905396
row=7, column=8 is empty
row=8, column=1, item=Echoist, confidence=0.9647416472434998
row=8, column=2, item=Overcharged, confidence=0.9559146761894226
row=8, column=3, item=Overcharged, confidence=0.9559146761894226
row=8, column=4, item=Rejuvenating, confidence=0.9368469715118408
row=8, column=5, item=Echoist, confidence=0.9647283554077148
row=8, column=6, item=Steel-Infused, confidence=0.9543660879135132
row=8, column=7, item=Deadeye, confidence=0.9633563756942749
row=8, column=8 is empty

Missing Items: []

**Comment by eric-engberg** [comment]
![image](https://user-images.githubusercontent.com/60901620/154815343-f028db3b-5238-41d0-adcf-683121f4b640.png)
![image](https://user-images.githubusercontent.com/60901620/154815352-9ed5539c-258c-457c-a2cb-03735fb192d1.png)

**Comment by 4rtzel** [comment]
I think it has something to do with incorrect scanning window calculations for your setup. The fact that column=8 was empty probably means that we didn't capture it properly.

Are you running standalone or manual installation?

**Comment by eric-engberg** [comment]
I download the release zip and use that

**Comment by trusql** [comment]
I have the same problem. It's not new, checked with v.0.2.0 and its the same. It's quite app-breaking to be honest. I also don't think it's related to resolution or other things because the results of this bug are not consistent. In the picture below, it always says column 8 is empty. And sometimes column 7 results are taken from column 8 (but NOT always, that's why I think it's not settings related, but something is wrong inside the main loop). I did some testings with confidence, but results were the same. HOWEVER, I found out that for column 7 it always shows the item that has higher confidence from column 7 and 8 ! So I guess something is wrong here.
![aas](https://user-images.githubusercontent.com/100050134/154821537-69111484-f5ed-49e2-88af-f92b4e23e517.png)

**Comment by 4rtzel** [comment]
I tried to fix this issue for 1920x1080 resolutions in a new v0.2.2. Could you try it and report back if it's fixed?

In case the issue is still present, could you launch the program with --show-capture-image option? It will display the image, that the program will use for scanning.

**Comment by trusql** [comment]
> I tried to fix this issue for 1920x1080 resolutions in a new v0.2.2. Could you try it and report back if it's fixed?
> 
> In case the issue is still present, could you launch the program with --show-capture-image option? It will display the image, that the program will use for scanning.

It works now! Good job

**Comment by eric-engberg** [comment]
It's fixed! Thank you!

**Comment by 4rtzel** [comment]
Closing the issue then.
